[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#070a12"
secondaryBackgroundColor = "#141b2b"
textColor = "#f4f7fb"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
